version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calendar-notification-bot
    restart: unless-stopped
    user: root
    volumes:
      - ./credentials.json:/app/credentials.json:ro
      - ./data:/data
    ports:
      - "4001:4001"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHECK_INTERVAL=${CHECK_INTERVAL}
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: calendar-notification-db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

volumes:
  postgres_data:
