version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calendar-notification-bot
    restart: unless-stopped
    user: root
    volumes:
      - ./credentials.json:/app/credentials.json:ro
      - ./data:/data
    ports:
      - "4001:4001"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHECK_INTERVAL=${CHECK_INTERVAL}
      - PYTHONUNBUFFERED=1
