version: '3'

tasks:
  restart:
    desc: Перезапуск контейнеров
    cmds:
      - docker compose down
      - docker compose up -d --build

  up:
    desc: Запуск контейнеров
    cmds:
      - docker compose up -d --build

  down:
    desc: Остановка контейнеров
    cmds:
      - docker compose down

  logs:
    desc: Просмотр логов
    cmds:
      - docker compose logs -f

  ps:
    desc: Просмотр запущенных контейнеров
    cmds:
      - docker compose ps

  clear:
    desc: Очистка контейнеров
    cmds:
      - docker compose down
      - docker system prune -f
      - docker rmi new_tg_notification-calendar-bot
      - docker system prune -f

  format:
    desc: "Форматирование кода с помощью black"
    cmds:
      - uv run black src/

  typecheck:
    desc: "Проверка типов с помощью mypy"
    cmds:
      - uv run mypy src/

  lint:
    desc: "Запуск форматирования и проверки типов"
    cmds:
      - task: format
      - task: typecheck
